######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 30 14:51:25 2014
######################################################################

TEMPLATE = app
TARGET = QtHelloWorld
DEPENDPATH += .
INCLUDEPATH += .
unix {
   CONFIG += link_pkgconfig
   PKGCONFIG += opencv
}

# Input
HEADERS += cvimagewidget.h
SOURCES += main.cpp
